### ISSUE TITLE
why don't you create an automation library with this

### ISSUE THREAD

**Issue by NCLnclNCL** [webdriverbidi-net/webdriverbidi-net#7]
currently there are only libraries using cdp and webdriver, i think webdriverbidi looks promising

**Comment by jimevans** [comment]
@NCLnclNCL Thank you for your interest in the project. As stated in the README, creating a general-purpose automation API is an explicit non-goal of this project. Several other browser automation libraries are mentioned in the README that could use this library to implement automation via the WebDriver BiDi protocol, or new ones with friendlier APIs could be created with this library as a basis.

**Comment by NCLnclNCL** [comment]
> @NCLnclNCL Thank you for your interest in the project. As stated in the README, creating a general-purpose automation API is an explicit non-goal of this project. Several other browser automation libraries are mentioned in the README that could use this library to implement automation via the WebDriver BiDi protocol, or new ones with friendlier APIs could be created with this library as a basis.

Why this need Chromedriver, i dont want it

**Comment by jimevans** [comment]
The library itself does not require chromedriver. It requires a running instance of Chrome that has an active listener that understands the WebDriver BiDi protocol. Likewise automating Firefox with this library does not require geckodriver. The “client” project in this repository is not production code, as mentioned in the README. It uses the “classic” browser drivers merely for convenience.

At present, the easiest way to get an instance of Chrome that understands the WebDriver BiDi protocol is to use chromedriver, but it’s not required. You could, for example, launch Chrome directly and instantiate [Google’s WebDriver BiDi listener](https://github.com/GoogleChromeLabs/chromium-bidi), but that requires creating a DevTools Protocol connection, creating a new Target, and executing script against that target (all via CDP) to initialize the listener. In the future, the Chrome developers may fold that functionality directly into the browser, which would remove the need for chromedriver, but you’d need to take that up with them.

Likewise, the “client” project here uses geckodriver to launch Firefox, mainly because the creation of an anonymous profile for Firefox is orthogonal to the use of WebDriver BiDi to drive the browser. Such a thing would be, or should be, very important to an actual automation library. But this library is not intended to be that.

Let me reiterate: **This project does _NOT_ require a browser driver.** The examples use them for convenience, nothing more.
